""""Constants for mpyl."""

RUN_ARTIFACTS_FOLDER = ".mpyl"
DEFAULT_CONFIG_FILE_NAME = "mpyl_config.yml"
DEFAULT_RUN_PROPERTIES_FILE_NAME = "run_properties.yml"

PR_NUMBER_PLACEHOLDER = "{PR-NUMBER}"
SERVICE_NAME_PLACEHOLDER = "{SERVICE-NAME}"
NAMESPACE_PLACEHOLDER = "{namespace}"
CLUSTER_ENV_PLACEHOLDER = "{CLUSTER-ENV}"

RUN_RESULT_FILE_GLOB = "run_result-*.pickle"
