---
$schema: https://json-schema.org/draft/2020-12/schema#
$ref: '#/definitions/Config'
definitions:
  Config:
    type: object
    properties:
      mpylVersion:
        description: >-
          The MINIMAL version of MPyL that should be used to build this project. If not
          specified, the latest version will be used.
        type: string
      vcs:
        $ref: '#/definitions/VCS'
      project:
        $ref: '#/definitions/Project'
    required:
      - vcs
    title: MPyL global configuration
  VCS:
    type: object
    properties:
      changedFilesPath:
        type: [string, null]
        description: Path to the file that contains the changed files
    title: VCS
  Project:
    type: object
    additionalProperties: false
    required:
      - allowedMaintainers
    properties:
      allowedMaintainers:
        type: array
        items:
          type: string
