---
name: Run MPyL
description: Action to run MPyL from a docker container
inputs:
  group:
    description: The command group to run
    required: true
  command:
    description: The command to run
    required: false
  environment:
    description: The environment this Action runs in
    required: true
  version:
    description: The version of the deliverable produced by the current workflow run
    required: true
  # to be replaced by environment, see https://vandebron.atlassian.net/browse/GUILD-1138
  deploy-target:
    description: The deploy target to use
    required: false
  config-path:
    description: The path to the MPyL config file
    required: false
  changed-files-path:
    description: The path to the file containing the changed files
    required: false
  commit:
    description: ???
    required: false
    default: ${{ github.sha }}

runs:
  using: docker
  image: docker://public.ecr.aws/vdb-public/gh-mpyl:v0.3.0
  args:
    - ${{ inputs.group }} ${{ runner.debug != '' && '--verbose' || '' }} ${{ inputs.command }}
  env:
    MPYL_CONFIG_PATH: ${{ inputs.config-path || 'mpyl_config.yml' }}
    CHANGED_FILES_PATH: ${{ inputs.changed-files-path }}
    TAG_NAME: ${{ inputs.environment != 'pull-request' && inputs.version || '' }}  # run_properties.versioning.tag
    GIT_COMMIT: ${{ inputs.commit }}  # run_properties.versioning.revision
    CHANGE_ID: ${{ github.event.pull_request.number }}  # run_properties.versioning.pr_number
    DEPLOY_TARGET: ${{ inputs.deploy-target }}  # run_properties.parameters.deploy_target
