---
name: mpyl
description: Action to run mpyl from a docker container

inputs:
  group:
    description: The command group to run
    required: true
  command:
    description: The command to run
    required: false
  debug:
    description: Whether to run mpyl in debug mode
    required: false
  config-path:
    description: The path to the mpyl config file
    default: mpyl_config.yml
  changed-files-path:
    description: The path to the file containing the changed files
    required: false

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.group }} ${{ inputs.debug != '' && '--verbose' || '' }} ${{ inputs.command }}
  env:
    MPYL_CONFIG_PATH: ${{ inputs.config-path }}
    CHANGED_FILES_PATH: ${{ inputs.changed-files-path }}
