[versions]
spring-boot = "2.7.18"
kotlin-spring-plugin = "1.8.22"


[plugins]
springFrameworkBootPlugin = { id="org.springframework.boot", version.ref = "spring-boot" }
springSependencymanagement = { id="io.spring.dependency-management", version = "1.1.4"}
kotlinSpringPlugin = { id="org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin-spring-plugin" }


[libraries]
spring-boot-starter = { group = "org.springframework.boot", name = "spring-boot-starter" }