---
vcs:
  changedFilesPath: !ENV ${CHANGED_FILES_PATH}
dagster:
  baseNamespace: dagster
  workspaceConfigMap: dagster-external-workspace-yaml
  workspaceFileKey: workspace.yaml
  daemon: dagster-daemon
  webserver: dagster-dagster-webserver
  globalServiceAccountOverride: global-dagster-user-deployment
project:  # default values
  allowedMaintainers: [Team1, Team2, MPyL]
