---
name: Run a MPyL stage
description: Run a MPyL stage inside a Docker container
inputs:
  project:
    description: The project to run
    required: true
  stage:
    description: The stage to run
    required: true
  environment:
    description: The environment this Action runs in
    required: true
  version:
    description: The version of the deliverable produced by the current workflow run
    required: true
  config-path:
    description: The path to the MPyL config file
    required: false
  # the following inputs do not actually need to be exposed, but since unfortunately we can't access the github or runner
  # context in runs.env.* we're forced to declare them as inputs
  commit:
    description: The commit SHA that triggered the current workflow run
    required: false
    default: ${{ github.sha }}
  pr-number:
    description: The pull request number (if applicable) that triggered the current workflow run
    required: false
    default: ${{ github.event.pull_request.number }}
  deploy-image:
    description: The Docker image to deploy
    required: false
runs:
  using: docker
  image: docker://public.ecr.aws/vdb-public/gh-mpyl:v0.6.1
  args:
    - build
    - --environment
    - ${{ inputs.environment }}
    - run
    - --stage
    - ${{ inputs.stage }}
    - --projects
    - ${{ inputs.project }}
    - --image
    - ${{ inputs.deploy-image }}
  env:
    MPYL_CONFIG_PATH: ${{ inputs.config-path }}
    CHANGED_FILES_PATH: ${{ inputs.changed-files-path }}
    TAG_NAME: ${{ inputs.environment != 'pull-request' && inputs.version || '' }} # run_properties.versioning.tag
    GIT_COMMIT: ${{ inputs.commit }} # run_properties.versioning.revision
    CHANGE_ID: ${{ inputs.pr-number }} # run_properties.versioning.pr_number
