---
name: Create a run plan
description: Create a run plan inside a Docker container
inputs:
  config-path:
    description: The path to the MPyL config file
    required: false
  changed-files-path:
    description: The path to the file containing the changed files
    required: true
  selected-project:
    description: The path to the file containing the changed files
    required: false
runs:
  using: docker
  image: docker://public.ecr.aws/vdb-public/gh-mpyl:v1.7.2
  args:
    - plan
    - discover
    - --project
    - ${{ inputs.selected-project }}
  env:
    MPYL_CONFIG_PATH: ${{ inputs.config-path }}
    CHANGED_FILES_PATH: ${{ inputs.changed-files-path }}
