---
name: Run MPyL health check
description: Perform MPyL health check inside a Docker container
inputs:
  config-path:
    description: The path to the MPyL config file
    required: false
runs:
  using: docker
  image: docker://public.ecr.aws/vdb-public/gh-mpyl:fix/broken-image-name-in-helm-tempalte
  args:
    - health
  env:
    MPYL_CONFIG_PATH: ${{ inputs.config-path }}
