---
name: Run MPyL health check
description: Perform MPyL health check inside a Docker container
inputs:
  config-path:
    description: The path to the MPyL config file
    required: false
runs:
  using: docker
  image: docker://ghcr.io/vandebron/docker-images/gh-mpyl:v1.10.0
  args:
    - health
  env:
    MPYL_CONFIG_PATH: ${{ inputs.config-path }}
