name: mpyl
description: Action to run mpyl from a docker container

inputs:
  command:
    description: The mpyl command to run
    required: true
  config-path:
    description: The path to the mpyl config file
    default: mpyl_config.yml
  changed-files-path:
    description: The path to the file containing the changed files
    required: false

runs:
  using: docker
  image: ../../Dockerfile
  args:
    - ${{ inputs.command }} ${{ env.ACTIONS_RUNNER_DEBUG == 'true' && '--verbose' || '' }}
  env:
    MPYL_CONFIG_PATH: ${{ inputs.config-path }}
    CHANGED_FILES_PATH: ${{ inputs.changed-files-path }}
