name: mpyl
description: Action to run mpyl from a docker container

inputs:
  mpyl-command:
    description: The mpyl command to run
    required: true
  image:
    description: The docker image to use
    default: ../../Dockerfile

runs:
  using: docker
  image: ${{ inputs.image }}
  args:
    - ${{ inputs.mpyl-command }}
