---
name: Create a run plan
description: Create a run plan inside a Docker container
inputs:
  config-path:
    description: The path to the MPyL config file
    required: false
  changed-files-path:
    description: The path to the file containing the changed files
    required: true
runs:
  using: docker
  image: docker://public.ecr.aws/vdb-public/gh-mpyl:v0.6.5
  args:
    - plan
    - create
  env:
    MPYL_CONFIG_PATH: ${{ inputs.config-path }}
    CHANGED_FILES_PATH: ${{ inputs.changed-files-path }}
