---
name: Generate Backstage components
description: Run MPyL to generate Backstage components
inputs:
  output-path:
    description: The output path
    required: true
  repository-url:
    description: The url of the repository
    required: true
  repository-name:
    description: The name of the repository
    required: true
runs:
  using: docker
  image: docker://public.ecr.aws/vdb-public/gh-mpyl:v1.8.4
  args:
    - backstage
    - generate
    - --output
    - ${{ inputs.output-path }}
    - --url
    - ${{ inputs.repository-url }}
    - --repository
    - ${{ inputs.repository-name }}
