---
name: Lint MPyL projects
description: Lint all known MPyL projects inside a Docker container
inputs:
  config-path:
    description: The path to the MPyL config file
    required: false
runs:
  using: docker
  image: docker://public.ecr.aws/vdb-public/gh-mpyl:v0.10.0
  args:
    - projects
    - lint
  env:
    MPYL_CONFIG_PATH: ${{ inputs.config-path }}
