---
name: Lint MPyL projects
description: Lint all known MPyL projects inside a Docker container
inputs:
  config-path:
    description: The path to the MPyL config file
    required: false
runs:
  using: docker
  image: docker://ghcr.io/vandebron/gh-mpyl/mpyl:v1.10.0
  args:
    - projects
    - lint
  env:
    MPYL_CONFIG_PATH: ${{ inputs.config-path }}
