name: from-dockerfile
on:
  push:

jobs:
  trial:
    name: Run from Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check mpyl health
        uses: ./.github/run-mpyl
        with:
          mpyl-command: health
          image: ../../Dockerfile
