---
name: from-dockerfile
on:
  workflow_dispatch:

jobs:
  example:
    name: Run from Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check mpyl health
        uses: ./
        with:
          group: health
