---
name: Validate Github Actions

on:
  workflow_call:
  pull_request:
    paths:
      - actions/**

# If multiple commits are pushed simultaneously, only build the last one.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:

  health:
    name: ▶️ Run actions/health
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: ./actions/health
        with:
          config-path: tests/test_resources/mpyl_config.yml

  projects:
    name: ▶️ Run actions/projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: ./actions/projects
        with:
          command: list
          config-path: tests/test_resources/mpyl_config.yml

  run-plan:
    name: ▶️ Run actions/run-plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: ./actions/run-plan
        with:
          environment: pull-request
          deploy-target: PullRequest
          version: a-random-version
          config-path: tests/test_resources/mpyl_config.yml
          changed-files-path: fixme-add-this-file-to-tests.json

  run-stage:
    name: ▶️ Run actions/run-stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: ./actions/run-stage
        with:
          project: minimalService
          stage: deploy
          environment: pull-request
          deploy-target: PullRequest
          version: a-random-version
          config-path: tests/test_resources/mpyl_config.yml
